foo/foo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls', namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foo/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="main/home.html"), name='home'),
    url(r'^pictures/$', views.PictureListView.as_view(), name='picture_list'),
    url(r'^pictures/(?P<pk>\d+)/$', views.PictureDetailView.as_view(), name='picture_detail'),
    url(r'^pictures/(?P<pk>\d+)/update/$', views.PictureUpdateView.as_view(), name='picture_update'),
    url(r'^pictures/create/$', views.PictureCreateView.as_view(), name='picture_create'),
    url(r'^pictures/(?P<pk>\d+)/delete/$', views.PictureDeleteView.as_view(), name='picture_delete'),
    url(r'^lists/$', views.ListListView.as_view(), name='list_list'),
    url(r'^lists/(?P<pk>\d+)/$', views.ListDetailView.as_view(), name='list_detail'),
    url(r'^lists/(?P<pk>\d+)/update/$', views.ListUpdateView.as_view(), name='list_update'),
    url(r'^lists/create/$', views.ListCreateView.as_view(), name='list_create'),
    url(r'^lists/(?P<pk>\d+)/delete/$', views.ListDeleteView.as_view(), name='list_delete'),
]

foo/main/models.py
from django.core.urlresolvers import reverse
from django.db import models

class Picture(models.Model):
    name = models.CharField(max_length=30, unique=True)
    img = models.ImageField(upload_to="img")

    def get_absolute_url(self):
        return reverse("main:picture_detail", kwargs={'pk': self.pk})
    
    def __str__(self):
        return self.name

class List(models.Model):
    name = models.CharField(max_length=30, unique=True)
    imgs = models.ManyToManyField(Picture, related_name="lists", blank=True)

    def get_absolute_url(self):
        return reverse("main:list_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

foo/main/forms.py
from django import forms
from .models import Picture, List

class PictureForm(forms.ModelForm):

    class Meta:
        model = Picture
        fields = "__all__"


class ListForm(forms.ModelForm):

    class Meta:
        model = List
        fields = "__all__"
        widgets = {
            'imgs': forms.CheckboxSelectMultiple()
        }

foo/main/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView
)
from .forms import PictureForm, ListForm
from .models import Picture, List

class PictureListView(ListView):
    model = Picture

class PictureCreateView(CreateView):
    model = Picture
    form_class = PictureForm

class PictureUpdateView(UpdateView):
    model = Picture
    form_class = PictureForm
    
class PictureDeleteView(DeleteView):
    model = Picture
    success_url = reverse_lazy('main:picture_list')
    
class PictureDetailView(DetailView):
    model = Picture

class ListListView(ListView):
    model = List

class ListCreateView(CreateView):
    model = List
    form_class = ListForm

class ListUpdateView(UpdateView):
    model = List
    form_class = ListForm

class ListDeleteView(DeleteView):
    model = List
    success_url = reverse_lazy('main:list_list')

class ListDetailView(DetailView):
    model = List

foo/main/templates/main/home.html
{% extends "base.html" %}

{% block content %}
{% endblock %}

foo/main/templates/main/list_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<p>Do you really want to remove this list?</p>
<form method="POST" action="">
  {% csrf_token %}
  <input type="submit" value="delete" />
</form>
{% endblock %}

foo/main/templates/main/list_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ object.name }}</h2>
<a href="{% url "main:list_update" pk=object.pk %}">update</a>
<a href="{% url "main:list_delete" pk=object.pk %}">delete</a>
<ul>
  {% for img in object.imgs.all %}
  <li>
	<a href="{{ img.get_absolute_url }}">{{ img.name }}</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

foo/main/templates/main/list_form.html
{% extends "base.html" %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

foo/main/templates/main/list_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url "main:list_create" %}" %}">create</a>

<ul>
  {% for list in object_list %}
  <li>
	<a href="{{ list.get_absolute_url }}">{{ list }}</a>
  </li>
  {% empty %}
  No list yet.
  {% endfor %}
</ul>
{% endblock %}

foo/main/templates/main/picture_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<p>Do you really want to remove this picture?</p>
<form method="POST" action="">
  {% csrf_token %}
  <input type="submit" value="delete" />
</form>
{% endblock %}

foo/main/templates/main/picture_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ object.name }}</h2>
<img src="{{ object.img.url }}" />
<a href="{% url "main:picture_update" pk=object.pk %}">update</a>
<a href="{% url "main:picture_delete" pk=object.pk %}">delete</a>
{% endblock %}

foo/main/templates/main/picture_form.html
{% extends "base.html" %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

{% endblock %}

foo/main/templates/main/picture_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url "main:picture_create" %}">create</a>

<ul>
  {% for picture in object_list %}
  <li>
	<a href="{{ picture.get_absolute_url }}">{{ picture }}</a>
  </li>
  {% empty %}
  No picture yet.
  {% endfor %}
</ul>
{% endblock %}

foo/templates/base.html
<!doctype html>
<html>
  <head>
  </head>
  <body>
	<header>
	  <h1>
		<a href="{% url "main:home" %}">Home</a>
	  </h1>
	</header>
	<nav>
	  <ul>
		<li><a href="{% url "main:picture_list" %}">Pictures</a></li>
		<li><a href="{% url "main:list_list" %}">Lists</a></li>
	  </ul>
	</nav>
	<div>
	  {% block content %}
	  {% endblock %}
	</div>
  </body>
</html>

foo/templates/django/forms/widgets/checkbox_select.html
Foo